project:
  type: website
  output-dir: docs
  
website:
  title: "Rhode Island Dept of Health"
  favicon: www/logo.png
  search: false
  navbar:
    background: dark
    logo: www/logo.png
    title: "Rhode Island Department of Health"
    pinned: true
  
format:
  html:
    theme: cosmo
    css: styles.css